### ISSUE TITLE
+ add block button invisible until hovered

### ISSUE THREAD

**Issue by aandrewjoyce** [ryelle/wp-core-color-list#4]
Gutenberg 'edit post' screen. The plus starts out as black on black and doesn't show up until hovered:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/10403517/94866395-dd0e1500-0404-11eb-8f5c-97a0e47f1d39.png">

**Comment by ryelle** [comment]
I think this is a bug with the version of Twenty Twenty that's installed, I'll get it updated so we can make sure.

**Comment by ryelle** [comment]
This looks fixed now, so it was a bug in the previous Twenty Twenty version.
