### ISSUE TITLE
Active Plugins need much more distinction

### ISSUE THREAD

**Issue by aandrewjoyce** [ryelle/wp-core-color-list#7]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/10403517/94869753-966fe900-040b-11eb-972e-c5bae2bc354f.png">

Can the color matching be over-ridden? The light blue should go to the lightest blue available, not to white.

**Comment by ryelle** [comment]
The lightest blue available is #f0f6fc, and the active plugin background (#f7fcfe) is ever-so-slightly closer to white. We can manually change it to use that light blue, which would be darker than core but not by a lot:

![Screen Shot 2020-10-01 at 6 38 05 PM](https://user-images.githubusercontent.com/541093/94870446-878e3400-0415-11eb-9a1e-b14d91c1af78.png)

**Comment by aandrewjoyce** [comment]
I'm a big fan of that. I don't think the blue is too dark -- if I don't compare side-by-side with current, I can't even notice a difference.

**Comment by ryelle** [comment]
I pushed a change to the branch to use `#f0f6fc`, so I'm going to close this issue. If anyone thinks the color needs to be tweaked we can open a new issue for it.
